version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydb
    depends_on:
      - db
    ports:
      - "3000:3000"
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && node dist/index.js"]

volumes:
  db-data:
